Use correct type for pthread entry point
This way we don't need to cast. Seems reasonable given that we want to treat
all warnings as errors. I got this one:

tests/mock/mock_threads.c:8:41: error: cast between incompatible function types from ‘void (*)(void *)’ to ‘void * (*)(void *)’ [-Werror=cast-function-type]
    8 |     pthread_create(&thread_temp, &attr, (void *(*)(void *))func, args);